name: notify_me
on:
  workflow_dispatch:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    steps:
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.PUSH_API_KEY }}
          MESSAGE: "There is a new commit!"
